# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jordan Shuck
email: jordan@shuck.org.uk
description: > # this means to ignore newlines until "baseurl:"
    Hi! I’m Jordan. BA (Hons) Television and Radio, MediaCityUK
10wordbio: BA (Hons) Television & Radio, University of Salford, MediaCityUK

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jordan.shuck.org.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

twitter_handle: jshuckie
youtube_handle: channel/UCVyJVvAwP48xrcMMCfANnyA
instagram_handle: jshuckie
flickr_handle: photos/jordan-shuck/
